package com.vish.gcart.entity;
// Generated Oct 23, 2020 10:52:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salefinaltable generated by hbm2java
 */
@Entity
@Table(name="salefinaltable"
    ,catalog="grocerycart"
)
public class Salefinaltable  implements java.io.Serializable {


     private Integer saleId;
     private int total;
     private Date date;

    public Salefinaltable() {
    }

    public Salefinaltable(int total, Date date) {
       this.total = total;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="saleId", unique=true, nullable=false)
    public Integer getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


