package com.vish.gcart.entity;
// Generated Oct 23, 2020 10:52:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Saletable generated by hbm2java
 */
@Entity
@Table(name="saletable"
    ,catalog="grocerycart"
)
public class Saletable  implements java.io.Serializable {


     private Integer salePk;
     private int saleId;
     private String item;
     private int quantity;
     private int price;

    public Saletable() {
    }

    public Saletable(int saleId, String item, int quantity, int price) {
       this.saleId = saleId;
       this.item = item;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salePK", unique=true, nullable=false)
    public Integer getSalePk() {
        return this.salePk;
    }
    
    public void setSalePk(Integer salePk) {
        this.salePk = salePk;
    }

    
    @Column(name="saleId", nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

    
    @Column(name="item", nullable=false)
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


